# CI de nivel 02 - Disparo agendado

# Nome do nosso 'pipeline'
name: 'CI - Execução Agendada'

# Regras de disparo (gatilho/triggers)
# Gatilho de execução agendada = schedule
# O cron é uma expressão que define a frequência de execução

on:
  schedule:
    # Gatilho de execução agendada
    # A expressão cron abaixo define que o trabalho será executado toda segunda-feira às 6:00 AM
    # Acesse o site https://crontab.guru/ para entender melhor a sintaxe do cron
    # Exemplo de cron: '0 6 * * 1' significa:
    # - 0 minutos
    # - 6 horas
    # - todos os dias do mês
    # - todos os meses
    # - 1 significa segunda-feira
    - cron: '0 6 * * 1'

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # Nome do trabalho
    name: 'E2E Tests'

    # Maquina/Ambiente onde o trabalho/job será executado
    runs-on: ubuntu-latest

    # Passos do script build
    # Cada passo é uma ação que será executada
    steps:
      # Ações do GitHub Actions
      # uses: é usado para ações pré-definidas do GitHub Actions
      # run: é usado para executar comandos diretamente no ambiente do runner

      # Clono do projeto
      # Ação de checkout do código fonte do repositório
      - uses: actions/checkout@v4

      # Instalacao do node
      - name: 'Setup Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' # Versão do Node.js a ser usada

      # Instalacao do Yarn
      - name: 'Instalando Yarn'
        run: npm install -g yarn

      # Instalação das dependências
      - name: 'Instalando dependencias'
        run: yarn

      # instalacap dp Playwright
      - name: 'Instalando Playwright'
        run: yarn playwright install
      # Execução dos testes E2E
      - name: 'Executando testes E2E'
        run: yarn run e2e